version: '3'


services:
  # Datastore
  postgres:
    env_file:
      - ./.envs/.local/.postgres
    build:
      context: . 
      dockerfile: ./compose/production/postgres/Dockerfile
    image: zca_local_postgres

  # Processor Application
  zca:
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.zca
    build:
      context: .
      dockerfile: ./compose/local/zca/Dockerfile
    image: zca_local_zca
    volumes:
      - ./zca:/zca
      - ./tests:/tests
    depends_on:
      - postgres
    command: /start
